language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
sudo: required
before_install: 
  - "sudo apt-get install -y libsnmp-dev snmp-mibs-downloader"
  - "sudo apt-get install -y autoconf libtool make libperl-dev python-dev"
install:
  - "python setup.py install"
script: 
  - "python scripts/tests.py"
